### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by TreeGrow** [YasuChiba/ros2-android-build#1]
Hello, I also recently tried to use ros2 on android, using the so and jar you generated, it feels great, thank you, but when I wanted to generate the so myself, I encountered a problem, I pulled this project, An error occurred during the docker build.
![image](https://user-images.githubusercontent.com/49939922/161190686-337aafc6-4adc-4c89-9c9c-0f84f525e5ff.png)
I don't know why this problem occurs.

**Comment by YasuChiba** [comment]
Thanks for your report. I fixed this issue.
Can you try it again?

**Comment by TreeGrow** [comment]
Wait a minute, I'll rebuild it now, thank you very much for your reply.

**Comment by TreeGrow** [comment]
Sorry to bother you again, I don't know where the problem is, I can't find the libc++_shared.so file, doesn't this project build jar and so... Why does this problem occur?
![image](https://user-images.githubusercontent.com/49939922/161904896-f1b653b1-940e-43ba-8f84-1a244b93ad0c.png)
